### ISSUE TITLE
拡張属性を消そう

### ISSUE THREAD

**Issue by biva8710** [uewolf25/unzip_files_script#1]
うちのボスなら以下の1行を追加するかと思われる
```bash
$ xattr -cr $(展開後のディレクトリ)
```

**Comment by uewolf25** [comment]
確かに、授業で言ってるの覚えてるわ
サンキュ

このスクリプト結局使ってへん笑
zip解凍時、同じファイル名鬼多いから分岐めんどいし、execコマンドで1行で済むからスクリプトって程のものでもなかった🙄

**Comment by biva8710** [comment]
ディレクトリの中にzip入れるんじゃなくて、ディレクトリを指定したらまだ使えるんちゃうかな？笑
まぁ確かにあんまり変わらんけど、、

**Comment by uewolf25** [comment]
あーなるほどな
ただ、解凍したファイルは全部同じディレクトリに入れてしまいたいから…って感じやな

**Comment by biva8710** [comment]
その辺はmvとかでなんとかできそうやけどどうやろ？
どんな構成を想定してて、どう楽したいのかがまだ見えてないから良い提案かわからんけども
